edition = "2021"
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
reorder_imports = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# they seem to be stable in nearest future, but for now we use it only for nightly CI check
comment_width = 100
condense_wildcard_suffixes = true
doc_comment_code_block_width = 100
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "One"
inline_attribute_width = 100
match_arm_blocks = false
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
version = "Two"
where_single_line = true
wrap_comments = true
