max_width = 100
array_width = 92
tab_spaces = 4
newline_style = "Unix"          # f*** windows style
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true

# they seem to be stable in nearest future, but for now we use it only for nightly CI check
unstable_features = true
condense_wildcard_suffixes = true
comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
fn_single_line = true
imports_granularity = "One"
match_arm_blocks = false
normalize_comments = true
wrap_comments = true
