name: CI

on:
  push:
    paths: ['**.rs', '**.toml', '**.lock', 'ci.yml', '**.sh']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', 'ci.yml', '**.sh']

env:
  CARGO_TERM_COLOR: always

jobs:
  build_from_tarball:
    name: full check
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          location: 'D:\M'
          pacboy: >-
            rust:p
            cmake:p
            ncurses:p
            desktop-file-utils:p
            freetype:p
            fontconfig:p
            ttf-dejavu:p
            git
      - name: hack rustup
        run: |
          rustup toolchain link msys2 D:\M\msys64\ucrt64
          rustup default msys2
      - name: build
        run: msys2 -c 'cargo b -v --locked'
      - name: clippy check
        run: msys2 -c cargo 'clippy --locked -- -D warnings'
      - name: test
        run: msys2 -c './.ci/tarball.sh'
