name: CI

on:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**/ci.yml', '**.sh']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**/ci.yml', '**.sh']

env:
  CARGO_TERM_COLOR: always

jobs:
  tarball_msys:
    name: build from tarball (MSYS2)
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          location: 'D:\M'
          pacboy: >-
            rust:p
            cmake:p
            ncurses:p
            desktop-file-utils:p
            freetype:p
            fontconfig:p
            ttf-dejavu:p
            diffutils:p
      - name: build
        run: msys2 -c 'cargo b -v --locked'
      - name: test
        run: msys2 -c './.ci/tarball.sh'
  lint_ubuntu:
    name: code check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: update to nightly rust
        run: |
          rustup update nightly
          rustup default nightly
          rustup component add rustfmt clippy
      - name: build
        run: cargo b -v --locked
      - name: fmt and clippy check
        run: cargo fmt -- --check; cargo clippy -- -D warnings
